### ISSUE TITLE
Non-Issue: Just wanted to compliment you on your solution

### ISSUE THREAD

**Issue by graydwarf** [Rowiz49/Godot_Solitaire#4]
I was looking at dabbling into some card/boardgame mechanics and thought solitaire would be a good start. As I got into it, I quickly realized it wasn't going to be straight forward due to mouse handling events. I tried a few different things but couldn't land on a solid implementation. I was about to go with a solution where I adjusted the hitbox to just the visible area depending on where it was in the stack. I think it would have worked for solitaire but felt it would come up short when I started working on other card games and mechanics. I started looking around for other ideas and came across your project and was pleasantly surprised by your solution. Processing all cards clicked and determining topmost is a clever way to deal with Area2D hover challenges. Just got started so looking forward to learning more from your project. Thanks for sharing it. I'll be watching for sure. Let me know if your on itch.io or twitter.

**Comment by Rowiz49** [comment]
Thank you for the compliment, you made my day. This was my second Godot project and this was an issue I spent so much time trying to fix as I didn't see any elegant solutions online. I created this repository in the off-chance that it would help someone and I'm glad it did. By the way, [this is my itch.io profile](https://rowiz49.itch.io/) :)
